version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "actions"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(actions)"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "npm"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Example: keep webextension-polyfill pinned unless security update
      - dependency-name: "webextension-polyfill"
        update-types: ["version-update:semver-major"]
