# AMO (addons.mozilla.org) validation configuration
# This file helps the automated validator understand the extension better

# Explain the innerHTML usage
notes: |
  This extension uses innerHTML in a controlled and safe manner:
  
  1. The extension capitalizes text that users type into editable fields
  2. innerHTML is used to read what the user already typed and write back the capitalized version
  3. All HTML content comes from the user's own input in their own browser
  4. The extension only modifies text capitalization, not HTML structure
  5. No user data is transmitted to servers or other users
  
  The innerHTML usage in bundled files comes from:
  - bootstrap.min.js: Trusted third-party library for UI tabs
  - main.bundle.js: Our code that reads and writes user's own editable content
  
  All innerHTML assignments are protected with eslint-disable-next-line no-unsanitized/property
  comments and detailed security explanations in the source code.
