import { names } from './name-constants';
import { abbreviations } from './abbreviation-constants';
import { locations } from './location-constants';

const days = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];

const months = [
  'January',
  'February',
  'April',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

const wordsWithApostrophe = {
  arent: 'aren\'t',
  cant: 'can\'t',
  couldnt: 'couldn\'t',
  couldve: 'could\'ve',
  didnt: 'didn\'t',
  doesnt: 'doesn\'t',
  dont: 'don\'t',
  hadnt: 'hadn\'t',
  hasnt: 'hasn\'t',
  havent: 'haven\'t',
  hed: 'he\'d',
  heres: 'here\'s',
  hes: 'he\'s',
  isnt: 'isn\'t',
  neednt: 'needn\'t',
  shes: 'she\'s',
  shouldnt: 'shouldn\'t',
  shouldve: 'should\'ve',
  thats: 'that\'s',
  theres: 'there\'s',
  theyd: 'they\'d',
  theyll: 'they\'ll',
  theyre: 'they\'re',
  theyve: 'they\'ve',
  werent: 'weren\'t',
  wheres: 'where\'s',
  whered: 'where\'d',
  whos: 'who\'s',
  wholl: 'who\'ll',
  wont: 'won\'t',
  wouldnt: 'wouldn\'t',
  wouldve: 'would\'ve',
  yall: 'y\'all',
  youd: 'you\'d',
  youre: 'you\'re',
  youve: 'you\'ve',
  youll: 'you\'ll',
};

const commonTechWords = [
  'Akamai',
  'Artifactory',
  'Baidu',
  'BigQuery',
  'BitTorrent',
  'Bluetooth',
  'Compaq',
  'CompuServe',
  'CosmosDB',
  'DevOps',
  'Drupal',
  'DynamoDB',
  'ECMAScript',
  'Emacs',
  'HBase',
  'Instagram',
  'JavaScript',
  'Jekyll',
  'Jenkins',
  'Jira',
  'LibreOffice',
  'MariaDB',
  'MongoDB',
  'MySQL',
  'Netscape',
  'NuGet',
  'NuGets',
  'Ocaml',
  'PagerDuty',
  'Perl',
  'PostgreSQL',
  'PowerPC',
  'PowerPoint',
  'PyTorch',
  'Redis',
  'Redshift',
  'SQLite',
  'Scala',
  'SharePoint',
  'TensorFlow',
  'Ubuntu',
  'Unicode',
  'Wii',
  'WordPress',
  'Xamarin',
  'iOS',
  'iPad',
  'iPhone',
  'iPod',
  'iTunes',
];

const commonTechAbbreviations = [
  '.NET',
  'ADFS',
  'AES',
  'AI',
  'API',
  'APIs',
  'CD',
  'CDN',
  'CI',
  'CIDR',
  'CLI',
  'CORS',
  'CSS',
  'DB',
  'DDoS',
  'DI',
  'DMS',
  'DNS',
  'DaaS',
  'DoS',
  'EHS',
  'EHW',
  'EMP',
  'ES',
  'FIFO',
  'FaaS',
  'HD',
  'HPC',
  'HTTP',
  'HTTPS',
  'HVM',
  'ICMP',
  'IOPS',
  'IP',
  'IPSec',
  'IaaS',
  'JS',
  'JSON',
  'LB',
  'MFA',
  'MITM',
  'ML',
  'MPLS',
  'MPP',
  'MSTSC',
  'MVC',
  'NAT',
  'NFS',
  'NS',
  'OLAP',
  'OLTP',
  'PCI',
  'PHP',
  'PR',
  'PRs',
  'PV',
  'PaaS',
  'RRS',
  'SAML',
  'SDK',
  'SLA',
  'SMS',
  'SOA',
  'SQL',
  'SSE',
  'SSH',
  'SSL',
  'SSO',
  'SUSE',
  'SVN',
  'SaaS',
  'TCP',
  'TLS',
  'TPM',
  'TPS',
  'TS',
  'TTL',
  'UA',
  'UAT',
  'UI',
  'UIs',
  'URL',
  'URLs',
  'VDI',
  'VLAN',
  'VM',
  'VPC',
  'VPN',
  'VPN',
  'VTL',
  'VoIP',
  'WAF',
  'WiFi',
  'iSCSI',
];

let awsAcronyms = [
  'ACL',
  'AMI',
  'ARN',
  'ASG',
  'AWS',
  'AZ',
  'CDK',
  'CF',
  'EBS',
  'EC2',
  'ECS',
  'EFS',
  'EIP',
  'ELB',
  'EMR',
  'ENI',
  'IAM',
  'IGW',
  'KMS',
  'RDS',
  'S3',
  'SES',
  'SNS',
  'SQS',
  'STS',
  'SWF',
  'VPC',
  'VPG',
];

let commonLocalAbbreviations = ['Syd', 'Melb'];

let constants = days.concat(
  months,
  commonTechWords,
  commonLocalAbbreviations,
  commonTechAbbreviations,
  awsAcronyms
);

let stringToKeyValuePairs = (obj, val) => {
  obj[val.toLowerCase()] = val;
  return obj;
};

let constantsMap = constants.reduce(stringToKeyValuePairs, {});

let toTitleCase = (str) => {
  return str.replace(/\w\S*/g, (txt) => {
    return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
  });
};

let wordsWithApostropheTitleCase = {};
for (const [key, value] of Object.entries(wordsWithApostrophe)) {
  wordsWithApostropheTitleCase[toTitleCase(key)] = toTitleCase(value);
}

//convert array to key-value pairs
export let constantsKeyValuePairs = {
  ...constantsMap,
  ...wordsWithApostrophe,
  ...wordsWithApostropheTitleCase,
};

export let namesKeyValuePairs = names.reduce(stringToKeyValuePairs, {});
export let abbreviationsKeyValuePairs = abbreviations.reduce(
  stringToKeyValuePairs,
  {}
);
export let locationsKeyValuePairs = locations.reduce(stringToKeyValuePairs, {});
